/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ArchitectureShowcaseRouteImport } from './routes/architecture-showcase'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdharKitIndexRouteImport } from './routes/adhar-kit/index'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogAuthRouteImport } from './routes/blog/auth'
import { Route as BlogAdminRouteImport } from './routes/blog/admin'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdharKitSplatRouteImport } from './routes/adhar-kit/$'
import { Route as BlogComposeIndexRouteImport } from './routes/blog/compose/index'
import { Route as ApiRolesIndexRouteImport } from './routes/api/roles/index'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as BlogComposeIdRouteImport } from './routes/blog/compose/$id'
import { Route as ApiProfilesMeRouteImport } from './routes/api/profiles/me'
import { Route as ApiProfilesIdRouteImport } from './routes/api/profiles/$id'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPostsIdIndexRouteImport } from './routes/api/posts/$id/index'
import { Route as ApiPostsIdModerateRouteImport } from './routes/api/posts/$id/moderate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureShowcaseRoute = ArchitectureShowcaseRouteImport.update({
  id: '/architecture-showcase',
  path: '/architecture-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdharKitIndexRoute = AdharKitIndexRouteImport.update({
  id: '/adhar-kit/',
  path: '/adhar-kit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/docs/api-reference',
  path: '/docs/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuthRoute = BlogAuthRouteImport.update({
  id: '/blog/auth',
  path: '/blog/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/blog/admin',
  path: '/blog/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdharKitSplatRoute = AdharKitSplatRouteImport.update({
  id: '/adhar-kit/$',
  path: '/adhar-kit/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComposeIndexRoute = BlogComposeIndexRouteImport.update({
  id: '/blog/compose/',
  path: '/blog/compose/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesIndexRoute = ApiRolesIndexRouteImport.update({
  id: '/api/roles/',
  path: '/api/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComposeIdRoute = BlogComposeIdRouteImport.update({
  id: '/blog/compose/$id',
  path: '/blog/compose/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesMeRoute = ApiProfilesMeRouteImport.update({
  id: '/api/profiles/me',
  path: '/api/profiles/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesIdRoute = ApiProfilesIdRouteImport.update({
  id: '/api/profiles/$id',
  path: '/api/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdIndexRoute = ApiPostsIdIndexRouteImport.update({
  id: '/api/posts/$id/',
  path: '/api/posts/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdModerateRoute = ApiPostsIdModerateRouteImport.update({
  id: '/api/posts/$id/moderate',
  path: '/api/posts/$id/moderate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/architecture-showcase': typeof ArchitectureShowcaseRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adhar-kit/$': typeof AdharKitSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog/auth': typeof BlogAuthRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/adhar-kit/': typeof AdharKitIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profiles/$id': typeof ApiProfilesIdRoute
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/blog/compose/$id': typeof BlogComposeIdRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/blog/compose/': typeof BlogComposeIndexRoute
  '/api/posts/$id/moderate': typeof ApiPostsIdModerateRoute
  '/api/posts/$id/': typeof ApiPostsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/architecture-showcase': typeof ArchitectureShowcaseRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adhar-kit/$': typeof AdharKitSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog/auth': typeof BlogAuthRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/adhar-kit': typeof AdharKitIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profiles/$id': typeof ApiProfilesIdRoute
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/blog/compose/$id': typeof BlogComposeIdRoute
  '/api/posts': typeof ApiPostsIndexRoute
  '/api/roles': typeof ApiRolesIndexRoute
  '/blog/compose': typeof BlogComposeIndexRoute
  '/api/posts/$id/moderate': typeof ApiPostsIdModerateRoute
  '/api/posts/$id': typeof ApiPostsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/architecture-showcase': typeof ArchitectureShowcaseRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adhar-kit/$': typeof AdharKitSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog/auth': typeof BlogAuthRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/adhar-kit/': typeof AdharKitIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profiles/$id': typeof ApiProfilesIdRoute
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/blog/compose/$id': typeof BlogComposeIdRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/blog/compose/': typeof BlogComposeIndexRoute
  '/api/posts/$id/moderate': typeof ApiPostsIdModerateRoute
  '/api/posts/$id/': typeof ApiPostsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/architecture-showcase'
    | '/capabilities'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/contributors'
    | '/examples'
    | '/integrations'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/adhar-kit/$'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog/auth'
    | '/docs/$'
    | '/docs/api-reference'
    | '/adhar-kit/'
    | '/blog/'
    | '/docs/'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/profiles/$id'
    | '/api/profiles/me'
    | '/blog/compose/$id'
    | '/api/posts/'
    | '/api/roles/'
    | '/blog/compose/'
    | '/api/posts/$id/moderate'
    | '/api/posts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architecture'
    | '/architecture-showcase'
    | '/capabilities'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/contributors'
    | '/examples'
    | '/integrations'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/adhar-kit/$'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog/auth'
    | '/docs/$'
    | '/docs/api-reference'
    | '/adhar-kit'
    | '/blog'
    | '/docs'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/profiles/$id'
    | '/api/profiles/me'
    | '/blog/compose/$id'
    | '/api/posts'
    | '/api/roles'
    | '/blog/compose'
    | '/api/posts/$id/moderate'
    | '/api/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/architecture-showcase'
    | '/capabilities'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/contributors'
    | '/examples'
    | '/integrations'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/adhar-kit/$'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog/auth'
    | '/docs/$'
    | '/docs/api-reference'
    | '/adhar-kit/'
    | '/blog/'
    | '/docs/'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/profiles/$id'
    | '/api/profiles/me'
    | '/blog/compose/$id'
    | '/api/posts/'
    | '/api/roles/'
    | '/blog/compose/'
    | '/api/posts/$id/moderate'
    | '/api/posts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ArchitectureShowcaseRoute: typeof ArchitectureShowcaseRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CareersRoute: typeof CareersRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  ContributorsRoute: typeof ContributorsRoute
  ExamplesRoute: typeof ExamplesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AdharKitSplatRoute: typeof AdharKitSplatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogAuthRoute: typeof BlogAuthRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  AdharKitIndexRoute: typeof AdharKitIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiProfilesIdRoute: typeof ApiProfilesIdRoute
  ApiProfilesMeRoute: typeof ApiProfilesMeRoute
  BlogComposeIdRoute: typeof BlogComposeIdRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
  ApiRolesIndexRoute: typeof ApiRolesIndexRoute
  BlogComposeIndexRoute: typeof BlogComposeIndexRoute
  ApiPostsIdModerateRoute: typeof ApiPostsIdModerateRoute
  ApiPostsIdIndexRoute: typeof ApiPostsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-showcase': {
      id: '/architecture-showcase'
      path: '/architecture-showcase'
      fullPath: '/architecture-showcase'
      preLoaderRoute: typeof ArchitectureShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhar-kit/': {
      id: '/adhar-kit/'
      path: '/adhar-kit'
      fullPath: '/adhar-kit/'
      preLoaderRoute: typeof AdharKitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/docs/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/auth': {
      id: '/blog/auth'
      path: '/blog/auth'
      fullPath: '/blog/auth'
      preLoaderRoute: typeof BlogAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/blog/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhar-kit/$': {
      id: '/adhar-kit/$'
      path: '/adhar-kit/$'
      fullPath: '/adhar-kit/$'
      preLoaderRoute: typeof AdharKitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/compose/': {
      id: '/blog/compose/'
      path: '/blog/compose'
      fullPath: '/blog/compose/'
      preLoaderRoute: typeof BlogComposeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/': {
      id: '/api/roles/'
      path: '/api/roles'
      fullPath: '/api/roles/'
      preLoaderRoute: typeof ApiRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/compose/$id': {
      id: '/blog/compose/$id'
      path: '/blog/compose/$id'
      fullPath: '/blog/compose/$id'
      preLoaderRoute: typeof BlogComposeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/me': {
      id: '/api/profiles/me'
      path: '/api/profiles/me'
      fullPath: '/api/profiles/me'
      preLoaderRoute: typeof ApiProfilesMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$id': {
      id: '/api/profiles/$id'
      path: '/api/profiles/$id'
      fullPath: '/api/profiles/$id'
      preLoaderRoute: typeof ApiProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id/': {
      id: '/api/posts/$id/'
      path: '/api/posts/$id'
      fullPath: '/api/posts/$id/'
      preLoaderRoute: typeof ApiPostsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id/moderate': {
      id: '/api/posts/$id/moderate'
      path: '/api/posts/$id/moderate'
      fullPath: '/api/posts/$id/moderate'
      preLoaderRoute: typeof ApiPostsIdModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  ArchitectureShowcaseRoute: ArchitectureShowcaseRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CareersRoute: CareersRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  ContributorsRoute: ContributorsRoute,
  ExamplesRoute: ExamplesRoute,
  IntegrationsRoute: IntegrationsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AdharKitSplatRoute: AdharKitSplatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogAuthRoute: BlogAuthRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  AdharKitIndexRoute: AdharKitIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiProfilesIdRoute: ApiProfilesIdRoute,
  ApiProfilesMeRoute: ApiProfilesMeRoute,
  BlogComposeIdRoute: BlogComposeIdRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
  ApiRolesIndexRoute: ApiRolesIndexRoute,
  BlogComposeIndexRoute: BlogComposeIndexRoute,
  ApiPostsIdModerateRoute: ApiPostsIdModerateRoute,
  ApiPostsIdIndexRoute: ApiPostsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
